### Creating sample data and saving the files

In [1]:
import os
import pandas as pd
import numpy as np

# Define folder paths relative to this notebook
raw_dir = os.path.join('..', 'data', 'raw')
processed_dir = os.path.join('..', 'data', 'processed')

# Create folders if they don't exist
os.makedirs(raw_dir, exist_ok=True)
os.makedirs(processed_dir, exist_ok=True)

# Define the sample data with more data points to ensure no NaN values present
data = {
    'age': [
        34, 45, 29, 50, 38, 41, 36, 47, 33, 40,
        31, 39, 42, 37, 44, 28, 35, 46, 32, 48,
        np.nan, 49, 30, np.nan, 43, 39, np.nan, 51, 34, np.nan
    ],
    'income': [
        55000, 62000, 42000, 58000, 50000, 49000, 53000, 61000, 47000, 56000,
        45000, 52000, 60000, 54000, 59000, 43000, 51000, 62500, 48000, 60500,
        50000, np.nan, 43000, np.nan, 57500, 49500, np.nan, 61500, 54000, np.nan
    ],
    'score': [
        0.82, 0.91, 0.75, 0.76, 0.88, 0.79, 0.85, 0.90, 0.80, 0.83,
        0.77, 0.86, 0.92, 0.81, 0.87, 0.74, 0.84, 0.89, 0.78, 0.91,
        0.80, 0.88, np.nan, np.nan, 0.86, 0.82, np.nan, 0.93, 0.85, np.nan
    ],
    'zipcode': [
        '90210', '10001', '60614', '94103', '73301', '94105', '33101', '02108', '30301', '77005',
        '20001', '98101', '15213', '48201', '53202', '97201', '43215', '63101', '55401', '70112',
        '10022', '60616', '30303', '94107', '73344', '33109', '02110', '77006', '20005', '98109'
    ],
    'city': [
        'Beverly', 'New York', 'Chicago', 'SF', 'Austin', 'San Francisco', 'Miami', 'Boston', 'Atlanta', 'Houston',
        'Washington', 'Seattle', 'Pittsburgh', 'Detroit', 'Milwaukee', 'Portland', 'Columbus', 'St. Louis', 'Minneapolis', 'New Orleans',
        'New York', 'Chicago', 'Atlanta', 'SF', 'Austin', 'Miami', 'Boston', 'Houston', 'Washington', 'Seattle'
    ],
    'extra_data': [
        np.nan, 42, np.nan, np.nan, np.nan, 5, 12, np.nan, 8, 15,
        20, np.nan, 18, 11, 13, np.nan, 10, 22, 7, 14,
        9, np.nan, 16, np.nan, 21, 19, np.nan, 17, 23, np.nan
    ]
}
# Create DataFrame
df = pd.DataFrame(data)
df['zipcode'] = df['zipcode'].astype('int')

# Save to CSV in raw data folder
csv_path = os.path.join(raw_dir, 'raw_data.csv')
if not os.path.exists(csv_path):
    df.to_csv(csv_path, index=False)
    print(f'Sample dataset created and saved to {csv_path}')
else:
    print(f'File already exists at {csv_path}. Skipping CSV creation to avoid overwrite.')

Sample dataset created and saved to ..\data\raw\raw_data.csv

### Pre-processing and cleaning the data

In [2]:
import sys
import os

src_path = os.path.abspath(os.path.join('..', 'src'))

if src_path not in sys.path:
    sys.path.append(src_path)

In [3]:
from cleaning import CleanData

In [4]:
# instanciating the class

clean = CleanData()

In [5]:
# missing value imputation

no_missing_data = clean.fill_missing_median(data_frame=df)
no_missing_data

     age   income  score  zipcode           city  extra_data
0   34.0  55000.0  0.820    90210        Beverly        15.0
1   45.0  62000.0  0.910    10001       New York        42.0
2   29.0  42000.0  0.750    60614        Chicago        15.0
3   50.0  58000.0  0.760    94103             SF        15.0
4   38.0  50000.0  0.880    73301         Austin        15.0
5   41.0  49000.0  0.790    94105  San Francisco         5.0
6   36.0  53000.0  0.850    33101          Miami        12.0
7   47.0  61000.0  0.900     2108         Boston        15.0
8   33.0  47000.0  0.800    30301        Atlanta         8.0
9   40.0  56000.0  0.830    77005        Houston        15.0
10  31.0  45000.0  0.770    20001     Washington        20.0
11  39.0  52000.0  0.860    98101        Seattle        15.0
12  42.0  60000.0  0.920    15213     Pittsburgh        18.0
13  37.0  54000.0  0.810    48201        Detroit        11.0
14  44.0  59000.0  0.870    53202      Milwaukee        13.0
15  28.0  43000.0  0.740    97201       Portland        15.0
16  35.0  51000.0  0.840    43215       Columbus        10.0
17  46.0  62500.0  0.890    63101      St. Louis        22.0
18  32.0  48000.0  0.780    55401    Minneapolis         7.0
19  48.0  60500.0  0.910    70112    New Orleans        14.0
20  39.0  50000.0  0.800    10022       New York         9.0
21  49.0  53500.0  0.880    60616        Chicago        15.0
22  30.0  43000.0  0.845    30303        Atlanta        16.0
23  39.0  53500.0  0.845    94107             SF        15.0
24  43.0  57500.0  0.860    73344         Austin        21.0
25  39.0  49500.0  0.820    33109          Miami        19.0
26  39.0  53500.0  0.845     2110         Boston        15.0
27  51.0  61500.0  0.930    77006        Houston        17.0
28  34.0  54000.0  0.850    20005     Washington        23.0
29  39.0  53500.0  0.845    98109        Seattle        15.0

In [6]:
# drop missing values

drop_missing_data = clean.drop_missing(no_missing_data)
drop_missing_data

     age   income  score  zipcode           city  extra_data
0   34.0  55000.0  0.820    90210        Beverly        15.0
1   45.0  62000.0  0.910    10001       New York        42.0
2   29.0  42000.0  0.750    60614        Chicago        15.0
3   50.0  58000.0  0.760    94103             SF        15.0
4   38.0  50000.0  0.880    73301         Austin        15.0
5   41.0  49000.0  0.790    94105  San Francisco         5.0
6   36.0  53000.0  0.850    33101          Miami        12.0
7   47.0  61000.0  0.900     2108         Boston        15.0
8   33.0  47000.0  0.800    30301        Atlanta         8.0
9   40.0  56000.0  0.830    77005        Houston        15.0
10  31.0  45000.0  0.770    20001     Washington        20.0
11  39.0  52000.0  0.860    98101        Seattle        15.0
12  42.0  60000.0  0.920    15213     Pittsburgh        18.0
13  37.0  54000.0  0.810    48201        Detroit        11.0
14  44.0  59000.0  0.870    53202      Milwaukee        13.0
15  28.0  43000.0  0.740    97201       Portland        15.0
16  35.0  51000.0  0.840    43215       Columbus        10.0
17  46.0  62500.0  0.890    63101      St. Louis        22.0
18  32.0  48000.0  0.780    55401    Minneapolis         7.0
19  48.0  60500.0  0.910    70112    New Orleans        14.0
20  39.0  50000.0  0.800    10022       New York         9.0
21  49.0  53500.0  0.880    60616        Chicago        15.0
22  30.0  43000.0  0.845    30303        Atlanta        16.0
23  39.0  53500.0  0.845    94107             SF        15.0
24  43.0  57500.0  0.860    73344         Austin        21.0
25  39.0  49500.0  0.820    33109          Miami        19.0
26  39.0  53500.0  0.845     2110         Boston        15.0
27  51.0  61500.0  0.930    77006        Houston        17.0
28  34.0  54000.0  0.850    20005     Washington        23.0
29  39.0  53500.0  0.845    98109        Seattle        15.0

In [7]:
# normalize the data

normalized_clean_data = clean.normalize_data(data_frame=drop_missing_data)

In [8]:
normalized_clean_data_columns = drop_missing_data.select_dtypes(np.number).columns.tolist()

for index in range(normalized_clean_data.shape[1]):
    drop_missing_data[normalized_clean_data_columns[index]] = normalized_clean_data[:,index]

In [9]:
drop_missing_data

         age    income     score   zipcode           city  extra_data
0  -0.834670  0.302298 -0.397099  1.149922        Beverly   -0.088593
1   0.919731  1.511488  1.389845 -1.414578       New York    4.132619
2  -1.632125 -1.943341 -1.786943  0.203658        Chicago   -0.088593
3   1.717187  0.820522 -1.588394  1.274392             SF   -0.088593
4  -0.196706 -0.561410  0.794197  0.609296         Austin   -0.088593
5   0.281767 -0.734151 -0.992746  1.274456  San Francisco   -1.652005
6  -0.515688 -0.043185  0.198549 -0.676008          Miami   -0.557617
7   1.238713  1.338746  1.191296 -1.666938         Boston   -0.088593
8  -0.994161 -1.079634 -0.794197 -0.765531        Atlanta   -1.182982
9   0.122276  0.475039 -0.198549  0.727723        Houston   -0.088593
10 -1.313143 -1.425117 -1.389845 -1.094850     Washington    0.693113
11 -0.037215 -0.215927  0.397099  1.402219        Seattle   -0.088593
12  0.441258  1.166005  1.588394 -1.247936     Pittsburgh    0.380430
13 -0.356197  0.129556 -0.595648 -0.193220        Detroit   -0.713958
14  0.760240  0.993263  0.595648 -0.033324      Milwaukee   -0.401276
15 -1.791616 -1.770600 -1.985493  1.373444       Portland   -0.088593
16 -0.675179 -0.388668  0.000000 -0.352636       Columbus   -0.870299
17  1.079222  1.597859  0.992746  0.283174      St. Louis    1.005795
18 -1.153652 -0.906893 -1.191296  0.036984    Minneapolis   -1.339323
19  1.398205  1.252376  1.389845  0.507335    New Orleans   -0.244935
20 -0.037215 -0.561410 -0.794197 -1.413906       New York   -1.026641
21  1.557696  0.043185  0.794197  0.203722        Chicago   -0.088593
22 -1.472634 -1.770600  0.099275 -0.765467        Atlanta    0.067748
23 -0.037215  0.043185  0.099275  1.274520             SF   -0.088593
24  0.600749  0.734151  0.397099  0.610670         Austin    0.849454
25 -0.037215 -0.647780 -0.397099 -0.675752          Miami    0.536771
26 -0.037215  0.043185  0.099275 -1.666874         Boston   -0.088593
27  1.876678  1.425117  1.786943  0.727755        Houston    0.224089
28 -0.834670  0.129556  0.198549 -1.094722     Washington    1.162136
29 -0.037215  0.043185  0.099275  1.402475        Seattle   -0.088593

In [10]:
# Save to CSV in raw data folder
processed_path = os.path.join(processed_dir, 'processed_data.csv')
if not os.path.exists(processed_path):
    drop_missing_data.to_csv(processed_path, index=False)
    print(f'Processed dataset created and saved to {processed_path}')
else:
    print(f'File already exists at {processed_path}. Skipping CSV creation to avoid overwrite.')

Processed dataset created and saved to ..\data\processed\processed_data.csv